name = "Steam Odyssey"
author = "BeetlesTheHunter"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "da25627a5542b571abe8f7e376cdd24a120f6634835f4042cf3dcdcfa7b79463"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
