name = "Steam Odyssey"
author = "BeetlesTheHunter"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8b3556c1a852ce028599d02e7f30749759c4d4881be0195fe393cdb333ab0684"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
