name = "Steam Odyssey"
author = "BeetlesTheHunter"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "72af9cca6f76262ae2528d556b1739df2668133c41a5fd5466d1641eba2b654f"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
